# Generated by Django 6.0.6 on 2026-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_location_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_fk',
        ),
        migrations.AddField(
            model_name='product',
            name='image_legacy',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('CLASSIFIED', 'Classified'), ('FIXED', 'Fixed Price')], default='FIXED', max_length=20, null=True),
        ),
    ]
