# Generated by Django 6.0.6 on 2026-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
